create book model, service, repository ,changed pom.xml
JeniaSan/Online-Book-Store pull request #1
Opened 2023-08-29 15:25 UTC by JeniaSan

and application.properties

2023-08-29 16:47 UTC, ConfusedSatlan approved these changes
good

2023-08-30 06:27 UTC, nacenik requested changes
Good solution, let's improve it :)

2023-08-30 06:27 UTC, nacenik commented on src/main/java/com/polishuchenko/bookstore/model/Book.java
> +
```suggestion
```

2023-08-30 06:27 UTC, nacenik commented on src/main/java/com/polishuchenko/bookstore/repository/impl/BookRepositoryImpl.java
> +    private SessionFactory sessionFactory;
Better make fields `final`
fix it everywhere

2023-08-30 06:27 UTC, nacenik commented on src/main/java/com/polishuchenko/bookstore/repository/impl/BookRepositoryImpl.java
> +            throw new RuntimeException("Can't get all books");
Throwing a general RuntimeException is not best practice.

2023-08-30 07:22 UTC, nacenik approved these changes
LGTM! 👍

2023-09-01 07:06 UTC, merged